### ISSUE TITLE
Implement a text editor

### ISSUE THREAD

**Issue by rdaoud1** [jlaverty/websiteDev#18]
We need to write a script that will have a text editor with the following functionality:
- update the `announcements.txt` file so the announcements section is easily updated

**Comment by rdaoud1** [comment]
This issue should be addressed by the following PR: https://github.com/jlaverty/websiteDev/pull/23

**Comment by jlaverty** [comment]
Text editor has been implemented for Keynotes and Announcements. Merge #26
